### ISSUE TITLE
Cloudflare Pages - Auth endpoints

### ISSUE THREAD

**Issue by whatisaghostwriter** [becem-gharbi/nuxt-auth#10]
I tried the registering using the cloudflare deployment you provided and I get a 400 error. I'm having the same error when deploying myself and was wondering if this issue is related to differences in deploying through Wrangler CLI versus automatic Git integration. 
![issue-auth](https://github.com/becem-gharbi/nuxt-auth/assets/34256092/6b3dd89d-f406-491e-b6d8-7183d26f2b0c)
I've deployed both "manually" and after connecting my github account to Pages. Interestingly the issue is more apparent when using automatic deployments. The function fails to upload with a seemingly obscure error and with manual it doesn't seem to capture the functions either although "_routes.json" exists.
![worker-failed](https://github.com/becem-gharbi/nuxt-auth/assets/34256092/c5e00a79-97bc-4118-bd80-0fea1730e81d)
My one question would be, what is the correct Base url to set for env, as I haven't seen this documented for Nuxt auth. should it include "https://" and does a leading slash at the end matter. Just trying to debug this to from what I've known 

Environment includes: 
* Pnpm@8.5.1
* Node 18 LTS
* Workers runtime version - --compatibility-date=2023-08-31
* For Pages automatic integration - Build system 2
* Nuxt Starter with no extra dependencies - as is

**Comment by becem-gharbi** [comment]
Hi, 

I agree that debugging for edge runtimes is tricky. The way I do this is by running the build command locally. Then I would run the application. If an error is thrown (in your case), I would search for its location on the server bundle (in your case it's 9295:39).

The baseURL should be a valid url, for example http://localhost:3000. With or without the trailing slash it doesn't matter.

Make sure that you have set `nitro.preset` in nuxt config to `cloudlflare-pages`.

**Comment by whatisaghostwriter** [comment]
I appreciate the quick response, can you verify that it doesn't work for any of the preview links you posted?
I have the same 400(Bad request) error and I've done everything to test it locally with no avail. Set DB_URL with mongodb, and synced schema with `prisma db push`.
Vercel edge https://nuxt-auth-demo.vercel.app/
Netlify edge https://nuxt-auth-demo.netlify.app/
Cloudflare pages https://nuxt-auth-c35.pages.dev/ 
It seems to be a malformed request/reponse object. I haven't tested out the Google Oauth option and just want email auth. Great project btw, I quite like the idea of edge workers.
This works for me https://nuxt-starter-app.bg.tn/auth/login?redirect=/
One last question, what would be `FROM email` format. **edit** Actually I see its just `demo@example.com`
I'm sure the problem is I haven't set an email sender, so I'll look into it the source code more to provide a custom one. Meanwhile I will use sendgrid to resolve the issue but I believe its one of the worst providers.

**Comment by becem-gharbi** [comment]
The demo works ok. Can you check the message error returned? Also, do you know any other email providers that support HTTP api?

**Comment by whatisaghostwriter** [comment]
Sure I found postmark to be quite pleasant but I haven't tested it yet. https://postmarkapp.com/developer/api/email-api. This plus cloudflare email routing should be a good combination for DNS/domain management. Btw in my original post, the first image is of the demo but the error is very ambiguous and is a 400 error(unsure how to get more in depth on the details)

**Comment by whatisaghostwriter** [comment]
> Sure I found postmark to be quite pleasant but I haven't tested it yet. https://postmarkapp.com/developer/api/email-api. This plus cloudflare email routing should be a good combination for DNS/domain management. Btw in my original post, the first image is of the demo but the error is very ambiguous and is a 400 error(unsure how to get more in depth on the details)

**EDIT** **`on the 400 error "prisma; database url must start with prisma//". I learned how to debug with browser console, and realized I did not setup up Prisma Data proxy, which seems to be the default option when using cloudfront pages.`**
Update on the email providers, I would like to propose that you add resend API. I've tested postmark and the drawbacks became more apparent along with the pricing. I think adding resend as the default email provider would make a lot of sense with ease of setup. I'd like to hear what you think of their pricing as well. It would help more people find this repo or at least consider it since a problem I had was not wanting to go through sendgrid and it completely went over my head when first setting up the environment variables. Its all good I can use the custom provider as well. https://resend.com/docs/api-reference/introduction. At least making mention of it in the docs would be a good move for SEO for more people to find this great repo. You can close this issue again

**Comment by becem-gharbi** [comment]
I prefer not to set a default provider because this would be subjective. Any provider that supports REST API can be supported by the module regardless of their pricing model. I agree that Postmark's free tier is very limited compared to others such as Sendgrid, Resend, Mailgun.. If no one requested it, it simply won't be added. Since you find Resend convenient (and me too), I will add it on the next release.
