### ISSUE TITLE
Use without Prisma?

### ISSUE THREAD

**Issue by nathanchase** [becem-gharbi/nuxt-auth#14]
Can this be used without Prisma? I already have a Python backend that is doing the authentication and returning the token, and I have no need to connect to a database.

**Comment by becem-gharbi** [comment]
Hi, at the moment this is not feasible. However I'm planning a frontend-only option in v2.4.

**Comment by hoanghiep1x0** [comment]
I'm also interested in a non-prisma version. I'm interested in mongodb. If possible, please upgrade without using prisma.

**Comment by becem-gharbi** [comment]
@hoanghiep1x0 Prisma does support Mongo DB. The module also provides a Frontend-only option if you need to use your backend [docs](https://nuxt-auth.bg.tn/getting-started/setup#frontend-only).

In version 3 I plan to introduce database adapters that allow database and ORM agnostic usage. I cannot make any promises regarding the release date as I currently don't have much time.

**Comment by hoanghiep1x0** [comment]
It's just that I'm familiar with mongodb queries so I don't want to switch to ORM. Thank you very much for this useful module.
