### ISSUE TITLE
How to get the Authorization Bearer token and verify with it.

### ISSUE THREAD

**Issue by hoanghiep1x0** [becem-gharbi/nuxt-auth#22]
I'm running web sockets and I need to support module authentication by retrieving and verifying tokens from your module. Every time I connect to the server, I will use the token provided by the nuxt-auth module. This will help the connection process.

I need a function to support getting and verifying tokens from your module. Can you upgrade the module's features?

**Comment by becem-gharbi** [comment]
If the Frontend-only option is disabled (the default), then the module internally verifies the access token. If valid, the payload is exposed via `event.context.auth` [Impl](https://github.com/becem-gharbi/nuxt-auth/blob/main/src/runtime/server/plugins/middleware.ts). If you intend to use the module's utility [functions](https://github.com/becem-gharbi/nuxt-auth/tree/main/src/runtime/server/utils), they can be imported from `#auth`. But note that they are not all typed and only [these](https://nuxt-auth.bg.tn/usage/utils) are.

**Comment by hoanghiep1x0** [comment]
I read your code and noticed I can get the token like this in component.vue
```

const { user ,getAccessToken}: { user: any } = useAuthSession();

const accessToken = await getAccessToken();
const headers = {
     "Authorization": `Bearer ${accessToken}`
}

```
Then I transmit it to the server with the socket when connecting.
I can then use the encode and decode functions from #auth.
I need it for websocket auth.

Can I use them like that?

**Comment by hoanghiep1x0** [comment]
i just saw these two functions getAccessTokenFromHeader
verifyAccessToken in server/utils/token/accessToken.ts seems to have exactly what I need but is it possible to use it in the project?

**Comment by becem-gharbi** [comment]
On client side, you can get a fresh access token with `getAccessToken`. On server side, you can directly check the payload with `event.context.auth`. The non documented server utilities are considered internals, you can use them but may be subject to unexpected changes.
