### ISSUE TITLE
Invalid access token on server-side with custom data fetching

### ISSUE THREAD

**Issue by hoanghiep1x0** [becem-gharbi/nuxt-auth#58]
Version "@bg-dev/nuxt-auth": "^3.0.2-rc" has an error when redirecting the page.

It automatically adds a character. http://localhost:3000 will be redirected when not logged in
http://localhost:3000/login?redirect=%25252F

http://localhost:3000/login?redirect=%25252F is a wrong path after logging in that will lead to a 404 page. and it has this error on most pages when not logged in. In version ^3.0.4-rc I see it doesn't have that error.

Versions "^3.0.2-rc" and "^3.0.4-rc" seem to have issues on the server-side with event.context.auth.data where sometimes there is data and sometimes there isn't.

Occasionally, there will be an error like /api/account/list Unauthorized.

while calling data from the client with the following code:

pages/account.vue

```bash
const { getAccessToken } = useAuthSession();

const accessToken = await getAccessToken();
const headers = {
  Authorization: `Bearer ${accessToken}`,
};
const limit = ref(20);
const page = ref(1);
const search = ref("");

const { data } = await useFetch("/api/accounts/list", {
  method: "GET",
  query: {
    page: page.value,
    limit: limit.value,
    search: search.value
  },
  watch: [page, limit, search],
  headers: headers
});
```

server/api/account/list.get.ts
```bash
import { UserModel } from '../../models'
export default defineEventHandler(async (event) => {
    try {
        // Get all request headers
        const userId = event.context.auth.data?.userId

        if (!userId) {
            return createError({ statusCode: 401, message: "unauthorized" })
        }

        const query = getQuery(event);

        // validate
        await pagination(query);

        const { page, limit, search, sort } = query;
        const pageNumber = page ?? 1;
        const limitNumber = limit ?? 10;
        const offset = (Number(pageNumber) - 1) * Number(limitNumber);

        var _condition = [{}]


        if (search) {
            _condition.push({ $or: [{ name: new RegExp(createSlug(search), "ig") }] });
        }

        var options = {
            select: "_id name email picture role verified suspended",
            // sort: { date: -1 },
            sort: {
                "createdAt": "desc"
            },
            lean: true,
            offset: offset,
            limit: limit,
        };

        return await UserModel.paginate({
            $and: _condition
        }, options);


    } catch (error) {
        console.log("error account list", error);
        return await createCustomError(500, "Error get account list")
    }
})
```

When I log the request in node_modules/@bg-dev/nuxt-auth/dist/runtime/server/utils/context.js

```bash
console.log("event",event.req.headers);
const accessToken = getAccessTokenFromHeader(event);
console.log("accessToken",accessToken);
```

result:
```bash
event { cookie:
   'auth_refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY2NzE3NzgzNWFmOGM2NDY3Y2ZlYjA2OCIsInVpZCI6IjVlNWU4NTg0LTAyMWUtNDM3OS1iMDdhLThmNjgwN2RhZjdjMSIsInVzZXJJZCI6IjY2NmU4Njk1YzEzMTEwNmZkODEyMWFkYyIsImV4cCI6MTcxOTMxNzc1MywiaXNzIjoibnV4dC1hdXRoIn0.Khp-0Vs8i6QPYCISHk8OSxGP7Xmcai-1wYHNtQrk_mU',
  'user-agent':
   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
  host: 'localhost' }
accessToken undefined
event { authorization:
   'Bearer eyJhbGciOiJIUzI1NiJ9.eyJzZXNzaW9uSWQiOiI2NjcxNzc4MzVhZjhjNjQ2N2NmZWIwNjgiLCJmaW5nZXJwcmludCI6IjRiMTI0MTkyZGI0MGE4M2ViMGUwZGY1MWMxN2IzODMzMzAwZmE4NzQiLCJ1c2VySWQiOiI2NjZlODY5NWMxMzExMDZmZDgxMjFhZGMiLCJ1c2VyUm9sZSI6InVzZXIiLCJwcm92aWRlciI6ImRlZmF1bHQiLCJ2ZXJpZmllZCI6dHJ1ZSwic3VzcGVuZGVkIjpmYWxzZSwiZXhwIjoxNzE5MzE3ODE5LCJpc3MiOiJudXh0LWF1dGgifQ.er2fT8u-7_omf_rpvmxzLeW_2GIw5LhhfeBEECuchO0',
  'user-agent':
   'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
  host: 'localhost' }
accessToken eyJhbGciOiJIUzI1NiJ9.eyJzZXNzaW9uSWQiOiI2NjcxNzc4MzVhZjhjNjQ2N2NmZWIwNjgiLCJmaW5nZXJwcmludCI6IjRiMTI0MTkyZGI0MGE4M2ViMGUwZGY1MWMxN2IzODMzMzAwZmE4NzQiLCJ1c2VySWQiOiI2NjZlODY5NWMxMzExMDZmZDgxMjFhZGMiLCJ1c2VyUm9sZSI6InVzZXIiLCJwcm92aWRlciI6ImRlZmF1bHQiLCJ2ZXJpZmllZCI6dHJ1ZSwic3VzcGVuZGVkIjpmYWxzZSwiZXhwIjoxNzE5MzE3ODE5LCJpc3MiOiJudXh0LWF1dGgifQ.er2fT8u-7_omf_rpvmxzLeW_2GIw5LhhfeBEECuchO0
verifyAccessToken { sessionId: '667177835af8c6467cfeb068',
  fingerprint: '4b124192db40a83eb0e0df51c17b3833300fa874',
  userId: '666e8695c131106fd8121adc',
  userRole: 'user',
  provider: 'default',
  verified: true,
  suspended: false,
  exp: 1719317819,
  iss: 'nuxt-auth' }
```
It seems that Nuxt will call data with useFetch twice, and the first time encountering a server error, Nitro will throw an unclear error like [unhandledRejection] write EPIPE.

I think when working with the server-side, the accessToken option of setting and getting it from the cookie and the second option of getting it from the Authorization headers should not encounter the above error.

One strange thing is that on the client side, it still retains the logged-in state, but when making a request to the API, sometimes it works and sometimes it doesn't. If you block the data retrieval, it will encounter an error where sometimes the data is fetched, and sometimes it is not.

**Comment by becem-gharbi** [comment]
First issue, page not found on login redirection: this is related to the encoding of the `redirect` query parameter introduced in #54 to fix infinite redirection on Vercel. With the release of `nuxt` v3.12.2 the issue is solved in core which led to this issue. A revert is introduced in c1d964b so you should upgrade to v3.0.4-rc.

Second issue, faulty server authorization: the access token verification process implements a fingerprint check [impl](https://github.com/becem-gharbi/nuxt-auth/blob/759d2273412bd955d9ae52acbe4d3dd88ae996ec/src/runtime/server/utils/token/accessToken.ts#L73). This ensures that user-agent is not modified. On client-side the `user-agent` is always set by the browser. However on server-side you'll need to manually pass it [impl](https://github.com/becem-gharbi/nuxt-auth/blob/759d2273412bd955d9ae52acbe4d3dd88ae996ec/src/runtime/plugins/provider.ts#L11). That's why it's highly recommended to use `useNuxtApp().$auth.fetch` for data fetching. You can combine it with `useAsyncData` to create a custom `useFetch` API. Please let me know if this solves the issue.

**Comment by hoanghiep1x0** [comment]
yes let me try it

**Comment by hoanghiep1x0** [comment]
Thank you, I have seen it working. Every request includes the accessToken. It is working well now. I would like to close this issue. Thank you very much.
