### ISSUE TITLE
How to add other properties to custom OAuth provider?

### ISSUE THREAD

**Issue by nathanchase** [becem-gharbi/nuxt-auth#59]
I have additional properties that my custom authorization backend requires:
```
scheme: 'oauth2',
responseType: 'code',
grantType: 'authorization_code',
accessType: 'offline',
clientId: process.env.AUTH_CLIENT_ID,
scope: ['openid'],
state: 'UNIQUE_AND_NON_GUESSABLE',
codeChallengeMethod: 'S256',
```
in addition to the ones OauthBase contains:
```
  clientId: string
  clientSecret: string
  scopes: string
  authorizeUrl: string
  tokenUrl: string
  userUrl: string
```
How would I ensure these additional properties get sent to my backend authorization via the query string, like the `scopes` and `clientSecret` does?

**Comment by becem-gharbi** [comment]
To log in with an OAuth provider the module implements this flow:

1. Via `authorizeUrl`: it requests an authorization code from the provider with `scope` to get user info and `state` to maintain the redirection path. The provider handles user authentication and consent.
2. Via `tokenUrl`: it requests an access token from the OAuth authorization server with the authorization `code` returned earlier.
3. Via `userUrl`: it requests user info with the access token returned earlier. The `scope` should permit getting the user `name` and `email` fields.
4. The module checks if the user exists (stored in the database), if not it registers him.
5. The module issues an access token and a refresh token for this new session. Note the tokens issued by the OAuth provider are not used, they are only needed to get user info.

The additional parameters you need to add are on the first step or the second?

*Reference: [Google](https://developers.google.com/identity/protocols/oauth2), [spec](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-00#page-24).*

**Comment by nathanchase** [comment]
> The additional parameters you need to add are on the first step or the second?

The first. The additional parameters need to be added to the query parameters of the `authorizeUrl`, similar to how it currently does with the `scope`.

**Comment by nathanchase** [comment]
See all of these additional parameters here on the Nuxt 2 auth module: https://auth.nuxtjs.org/schemes/oauth2
```
auth: {
  strategies: {
    social: {
      scheme: 'oauth2',
      endpoints: {
        authorization: 'https://accounts.google.com/o/oauth2/auth',
        token: undefined,
        userInfo: 'https://www.googleapis.com/oauth2/v3/userinfo',
        logout: 'https://example.com/logout'
      },
      token: {
        property: 'access_token',
        type: 'Bearer',
        maxAge: 1800
      },
      refreshToken: {
        property: 'refresh_token',
        maxAge: 60 * 60 * 24 * 30
      },
      responseType: 'token',
      grantType: 'authorization_code',
      accessType: undefined,
      redirectUri: undefined,
      logoutRedirectUri: undefined,
      clientId: 'SET_ME',
      scope: ['openid', 'profile', 'email'],
      state: 'UNIQUE_AND_NON_GUESSABLE',
      codeChallengeMethod: '',
      responseMode: '',
      acrValues: '',
      // autoLogout: false
    }
  }
}
```

**Comment by becem-gharbi** [comment]
This is now possible via `customParams` https://nuxt-auth.bg.tn/configuration/oauth.html. Please make sure to check the already used params.
https://github.com/becem-gharbi/nuxt-auth/blob/cce57bdc86d3dadd45195a8247e40de66202ec18/src/runtime/server/api/login/%5Bprovider%5D.get.ts#L29

```
npm install @bg-dev/nuxt-auth@edge
```
